<h1 style="font-size: 32px; text-align: center;">Introduction to Computer Programming for the Physical Sciences</h1>
<h2 style="font-size: 24px; text-align: center;">Diego Gonzalez Hernandez</h2>
<h3 style="font-size: 24px; text-align: center;">Spring 2025</h2>

## Working on Section Problems

<ul style="list-style: none;">
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;"></span>Get into groups of 2 or 3, with at least one laptop per group.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;"></span>Discuss with each other and attempt each problem yourselves first without AI support for 10-15 mins.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;">
</span>Input the problem prompt into the AI chatbox, use its answer to verify your own, or to learn how it should be solved.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;">
</span>For section problems, you can omit most of the commenting and focus on learning coding. For more difficult problems, minimal comments are still recommended as a way of organizing your own thoughts.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;"></span>Please abide by the <b><a href="https://github.com/enigma-igm/Phys29/blob/main/using_AI_tools.md">Policy and Guidelines on Using AI Tools</a></b></li>

# Section 4

## Problem 1

1. Write a function with a for loop inside it to return the factorial of x, f (x) = x!, where x is passed in as an argument.

2. Write a function using recursion to return the factorial of an argument, f (x) = x!, by implementing the recursion relation f (0) = 1, f (n) = nf (n − 1).

In [9]:
# your solution here

# For Loop Method

def fact_for(x):
    """
    Calculate the factorial of x using a "for loop"

    Parameters:
        x - Integer for which we want to calculate the factorial; int

    Output:
        fact - Factorial of integer x; int
    """

    # Create a variable to hold the factorial value
    fact = 1

    # Iterate through integers from 1 to x
    for i in range(1,x+1):

        # Update the factorial value with the next integer
        fact = fact*i

    return fact
        

def fact_rec(x):
    """
    Calculate the factorial of x using a "recursion loop"

    Parameters:
        x - Integer for which we want to calculate the factorial; int

    Output:
        fact - Factorial of integer x; int
    """

    # If x is greater than 0, iterate through the recursion loop
    if x > 0:

        # Return the value of x times this function for x-1
        return x*fact_rec(x-1)

    # If x is <= 0; then return 1. This will signify the END of the recursive loop
    else:

        return 1


In [10]:
import numpy as np

print(np.math.factorial(7))
print(fact_for(7))
print(fact_rec(7))


5040
5040
5040


## Problem 2

Compute the sum of the even numbers between 2 and 100 (inclusive) four ways:

• Use a for loop over the integers
    
• Create an array from 2 to 100 using numpy.arange() with a step size of 2, then
sum it using numpy.sum()

• Create an array from 1 to 50 using numpy.arange(), double it, and sum it

• Create an array from 0 to 100 and take every second element, then sum it

In [13]:
# your solution here

# Method 1

ints = range(0,101) # Generate the set of integers

even_sum_1 = 0 # Instantiate our sum variable

for num in ints: # Loop over each integer

    # Check if the integer is even by checking to see if the remainder of num/2 is 0; 
    # In python, % is the "modulus" or "remainder" operator
    if num%2 == 0: 

        even_sum_1 += num # If even, add the number to our sum variable

print(even_sum_1) # Print the final sum variable after the loop


# Method 2

# Create an "array" of integers from 2 to 100 with step size of 2; i.e. 2,4,6...98,100
even_arr = np.arange(2,101,2) 

# Use the "sum" function of the array class to quickly find the sum of the entire array
even_sum_2 = even_arr.sum() 

print(even_sum_2) 


# Method 3

half_arr = np.arange(1,51) # Create an array of integers from 1 to 50

double_arr = 2 * half_arr # Double the value of each integer in the array

even_sum_3 = double_arr.sum() # Calculate the sum of the full array

print(even_sum_3)


# Method 4

full_arr = np.arange(0,101) # Generate an array of integers from 0 to 100

# Using indexing, select every second element from the full array and store them a new array "sliced_arr"
sliced_arr = full_arr[::2] 

even_sum_4 = sliced_arr.sum() # Calculate the sum of the sliced_array

print(even_sum_4)


2550
2550
2550
2550


## Problem 3

Generate 5 random number from a Gaussian distribution of mean 6 and standard deviation 3. (Google numpy functions and find the right ones to use)

In [18]:
# your solution here

# In numpy, there is a module called "random" which has access to multiple methods of generating random numbers
# The Gaussian, or Uniform, distribution can be accessed through the numpy.random.normal function

# Note that loc=mean; scale=standard deviation; and size=number (or a multi-dimensional array of random numbers)
print(np.random.normal(loc=6,scale=3,size=5))

# You do not need to remember the specific parameter names, the specific order is all that is required.
print(np.random.normal(6,3,5)) 

# Lastly note that we can shorten this function call by specifically importing the random module thusly:

from numpy import random as rand

print(rand.normal(6,3,5))

# In fact, we can use this notation to import ONLY the normal function if we so desired 
# (note that in general this usually isn't your best option when writing code)

from numpy.random import normal

print(normal(6,3,5))


[ 7.66309063 -0.14371933  6.67291279  7.25355616  7.19520954]
[ 6.41683628  2.20331153  4.64628304  8.47105647 -0.07910437]
[8.34905607 3.01072706 2.58218596 8.75575826 6.84212353]
[7.28046023 5.82299722 3.50798702 5.6027227  0.58483271]


## Problem 4

This problem will give a very brief introduction to multidimensional arrays.

• Using np.array, create a 3 × 3 numpy array called x with first row 0, 1, and 2; second row 3, 4, and 5; and third row 6, 7, and 8.

• Do the same thing by first creating a one dimensional array of nine elements using np.arange, and then np.reshape; the new shape will be (3, 3).

• How do you index the central element 4 of your 3 × 3 array x?

• For multidimensional arrays, np.sum can also take an argument known as axis. Execute the following code on your 3 × 3 array x:
```
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
```
What does np.sum with no axis argument do? What are the axis=0 and axis=1 arguments doing?

In [29]:
# your solution here

# Method 1

int_list = [[0,1,2],[3,4,5],[6,7,8]] # Generate a 3x3 list of integers from 0 to 8

int_arr = np.array(int_list) # Use numpy.array to convert this list into an array

print(int_arr)


# Method 2

int_arr_1d = np.arange(9) # Generate a range of integers from 0 to 8


# Use numpy.reshape to take the 1D array and change it into a 2D array of size 3x3.
int_arr_2d = np.reshape(int_arr_1d,(3,3)) 


# Note that the order of the elements of the 2D array is filled in the following manner: 
#
# [0,0], [0,1], [0,2], [1,0], [1,1], [1,2], [2,0], [2,1], [2,2]
#  ||     ||     ||     ||     ||     ||     ||     ||     ||
#   0,     1,     2,     3,     4,     5,     6,     7,     8


print(int_arr_2d)


# Following the notation shown above for how the reshaping of the 1D array into a 2D array 
# assigns elements to specific indices, we see that the central value occurs in the 2nd position
# of the 2nd array; hence index [1,1]:
print(int_arr_2d[1,1])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


In [30]:


x = int_arr_2d # Assign the 2D array to variable "x"

print(np.sum(x)) # This use of np.sum finds the TOTAL sum of all elements in the array



print(np.sum(x, axis=0)) 
# This use of np.sum finds the sum along axis=0, i.e. the first index we use [(this one), (not this one)]
# So, given some value in the 2nd index, we find the sum of all values that contain that index.
# In the case of that value being 0; we have the sum of [0,0], [1,0], and [2,0] for the first value.
# In the resulting array, this value will be stored in the 0th index position result[0]
# Practically, this example gives 9 as the three values shown above give 0+3+6=9



print(np.sum(x, axis=1))
# This example works exactly the same as the above example, only now the axis we sum along is changed.
# So again, given index value zero, now we have the sum of [0,0], [0,1], [0,2] for the first value.
# In the resulting array, this value will be stored in the 0th index position result[0]
# Practically, this example gives 3 as the three values shown above give 0+1+2=3


36
[ 9 12 15]
[ 3 12 21]
