# Introduction to Numpy

Thus far we have seen that the Python programming language has the control flow structures (conditional statements, loops, etc.) that allow us to perform numerical calculations. When we discussed python data containers (lists, tuples, dictionaries) we gave examples of 
data that we might need to maniuplate in physics: 
  - vectors: $\mathbf{r} = \begin{pmatrix}x\\y\\z\end{pmatrix}$
  - matrices: $\mathsf{A} = \begin{pmatrix}
       A_{11} & A_{12} & A_{13}\\
       A_{21} & A_{22} & A_{23}
       \end{pmatrix}$
  - tensors: $\epsilon_{ijk}$
  - time series of position measurements: $\big\{x(t_1), x(t_2), \dots, x(t_N)\big\}$
  - measurements at specific coordinates e.g., 
  - a density field, which is a scalar function of cartesian coordinate in space: $\rho(x,y,z)$
  - The temperature on the Earth's surface as a function of latitude/longitude: $T(\phi, \theta)$

It is possible to represent all of these data structures using native python data containers, for example, a vector can be represented as a list of numbers, a matrix as a list of lists, with the first list representing the rows of the matrix, and the second list representing the columns. However, it turns out that this is not a very efficient way to represent these data structures in computer memory, and it is not the most efficient way to perform numerical calculations on these data structures.

When it comes to doing numerical work, Python by itself is rather slow. Recall from the Week1 lecture that programming languages come in two flavors,  **interpreted** languages like Python and **compiled** languages like C and Fortran. The preprocessing of a program into machine code by a compiler makes compiled languages far more efficient at storing data and performing numerical calculations. The flexiblity and ease of use that come with an interpreted language like Python, whereby each line of code is interpreted in sequence then executed,  comes at the cost of pure performance.

However, although Python code alone may be slow, Python can be used to write and run code that is effectively calling a compiled language under the hood. This gives us the flexibility and ease of use of Python, but, for specific applications,  the performance of a compiled language. This is the approach taken by the [Numpy](https://numpy.org/) python package, which is a code library that provides one of the foundations of the Python scientific computing ecosystem. The specific context for which the Numpy library is designed to be applied to is  fast and efficient manipulation and computation with numerical arrays.

As we have already discussed, we can import the `numpy` package and rename it to the very common shorthand `np`:

In [2]:
import numpy as np

The core data structure that `numpy` provides is known as the `numpy` array:

In [3]:
somenums = np.array([1, 2, 3, 4])
print(somenums)

[1 2 3 4]


A numpy array looks superfically similar to a `list`, which is a native Python data structure. Indeed, if you look closely at the line above, we are actually passing a Python `list` to the `np.array` function to create the array for this particular example of array initialization.  Lists and `numpy` arrays are however, fundamentally different, both in how they work and how they exist in memory. Unlike native Python objects, `numpy` arrays don't store references to other objects, but instead point to contiguous blocks of memory in which each element is of exactly the same data type. For instance, we just made an array of 64 bit integers:

In [4]:
somenums.dtype

dtype('int64')

In [5]:
# this will give an array of 64 bit floats
floats = np.array([63.3, -5.0, 1])
print(floats)

[63.3 -5.   1. ]


In [6]:
floats.dtype

dtype('float64')

## Array Methods: Arrays are Objects!

`numpy` arrays are optimized for fast numerical operations. Like everything in Python these are *objects*, they include built-in methods such as:

In [ ]:
somenums.sum()

np.int64(10)

Which computes the sum of all the elements in the array $\mathbf{x}$:
$$ 
{\tt sum} = \sum_{i=0}^{N-1} x_i
$$
or 

In [8]:
somenums.mean()

np.float64(2.5)

which computes the average of all the elements in the array $\mathbf{x}$:
$$
{\tt mean} = \frac{1}{N}\sum_{i=0}^{N-1} x_i
$$

and a whole plethora of others. You can get a view of what methods and attributes are part of an array's method/attribute namespace with:

In [9]:
dir(somenums)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [10]:
np.sum(somenums)

np.int64(10)

or in the notebook, by typing the name of the array followed by a `.` and the ```<TAB>``` key:
``` python 
In [1]: somenums.<TAB>
    all()          ctypes         item()         real           swapaxes()    
    any()          cumprod()      itemset()      repeat()       T             
    argmax()       cumsum()       itemsize       reshape()      take()        
    argmin()       data           max()          resize()       tobytes()     
    argpartition() diagonal()     mean()         round()        tofile()      
    argsort()      dot()          min()          searchsorted() tolist()      
    astype()       dtype          nbytes         setfield()     tostring()    
    base           dump()         ndim           setflags()     trace()       
    byteswap()     dumps()        newbyteorder() shape          transpose()   
    choose()       fill()         nonzero()      size           var()         
    clip()         flags          partition()    sort()         view()        
    compress()     flat           prod()         squeeze()                    
    conj()         flatten()      ptp()          std()                        
    conjugate()    getfield()     put()          strides                      
    copy()         imag           ravel()        sum()                        
```

Recall that you can also get the documentation for any function or method with a question mark at the end of the name:

``` python
In [5]: somenums.mean?
Docstring:
a.mean(axis=None, dtype=None, out=None, keepdims=False, *, where=True)

Returns the average of the array elements along given axis.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.mean : equivalent function
Type:      builtin_function_or_method
```

In [11]:
somenums.mean?

Docstring:
a.mean(axis=None, dtype=None, out=None, keepdims=False, *, where=True)

Returns the average of the array elements along given axis.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.mean : equivalent function
Type:      builtin_function_or_method

## Multidimensional Arrays, Indexing, and Slicing

`numpy` arrays can be of any dimensionality, not just 1D. 

### ndarrays 

It's common to encounter 2-D arrays, which are often used to represent matrices. For example, we can create a 2D array by passing a list of lists (nested list) to the `np.array` function. 

Make a 2D array to represent the matrix: 
$$
\mathsf{A} = \begin{pmatrix}
                A_{00} & A_{01}\\
                A_{10} & A_{11}
             \end{pmatrix}     = \begin{pmatrix}
                1 & 2\\
                3 & 4
               \end{pmatrix}, 
$$
where we are using *zero-based* indexing, so that $A_{00}$ is the element in the first row and first column of the matrix.

In [12]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [13]:
A.ndim

2

In [14]:
A.shape

(2, 2)

In [15]:
A.dtype

dtype('int64')

Arrays are made by rows, i.e. `A[0]` is the first row, `A[1]` is the second row, etc.:

In [16]:
A[0]

array([1, 2])

In [17]:
A[1]

array([3, 4])

Indexing notation:
- we separate **axes** (dimensions) by commas
- a `:` gives sub-arrays or elements via the slicing we learned about when discussing lists and tuples. 

The convention is `A[row,column]`, i.e. 

In [18]:
A[0, 0]

np.int64(1)

In [19]:
A[0, 1]

np.int64(2)

In [20]:
A[1, 1]

np.int64(4)

Slicing `numpy` arrays uses the same notation and conventions that we learned for lists. For instance, the first dimension is the row dimension, and the second dimension is the column dimension. To access the second column of the matrix, we can use the following syntax:

In [21]:
A[:, 1]

array([2, 4])

Likewise the first row of the matrix is:

In [22]:
A[0, :]

array([1, 2])

and this expression, `A[0,:]` for the first row is equivalent to:

In [23]:
A[0]

array([1, 2])

What about a 3D array?

In [24]:
A1D = np.arange(24)  # 1D array with 24 elements, i.e. A1D = 0, 1, ..., 23
B = A1D.reshape((2, 4, 3))  # Reshape to be 3D that is 2x4x3

In [25]:
print('The dimensionality is:', A1D.ndim)
print('The shape is:', A1D.shape)
print('A1D =', A1D)

The dimensionality is: 1
The shape is: (24,)
A1D = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


The 3D array is packaged as 2 2D arrays of shape 4x3:

In [26]:
print('The dimensionality is:', B.ndim)
print('The shape is:', B.shape)
print('B =', B)

The dimensionality is: 3
The shape is: (2, 4, 3)
B = [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


The *representation* of this 3D array, i.e. what we see when we print it, is a list of 2D arrays, each of which is represented by a list of the rows (1D arrays). So we  have a list of lists of lists. Clearly the numpy indexing is the easier way to think about and access the elements of arrays.

If we want to access the second sub-array, which is itself a 2D 4x3 array, we can use the following syntax:

In [27]:
print(B[1].shape)
print('B[1] =', B[1])

(4, 3)
B[1] = [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


The dimensionality of the 3D array `B` is `ndim = 3`, and the shape of this array is thus a tuple of length 3, `shape=(2,4,3)`, which is the size of the array in each of the 3 dimensions. We refer to each of these dimensions as an **axis** of the array, and the axes are numbered from 0 to `ndim-1`, so in this case the axes are numbered 0, 1, and 2. If we want to access every other element of the array along the `axis=1`, we can use the following slicing and striding syntax that we learned for lists:  

In [30]:
B[:,::2,:]

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[12, 13, 14],
        [18, 19, 20]]])

Which is equivalent to:

In [31]:
B[:, ::2]

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[12, 13, 14],
        [18, 19, 20]]])

since omitting an axes (`axis=2`) from the slice notation results in a slice that includes all the elements along that axis. 

Note that the shape is now `(2,2,3)` as compared to the original shape of `(2,4,3)`: because we have selected every other element along the `axis=1`, which has the effect of reducing the size of the array along that axis by a factor of 2.

In [32]:
B[:, ::2].shape

(2, 2, 3)

### Example: A Particle Trajectory 

For illustration we will write some code to represent the position of a particle in three dimensions as a function of time with a `numpy` array.  Consider the following trajectory:
$$
\mathbf{r}(t) = \begin{pmatrix}
                x(t)\\
                y(t)\\
                z(t)
                \end{pmatrix} =  
                \begin{pmatrix}
                \cos{t}\\
                \frac{t}{5} + \sin{\frac{t}{2}}\\
                2t + 2\sin{t}
                \end{pmatrix}~{\rm m}, 
                $$
Defined over the interval of time $t\in[0,4\pi]~{\rm s}$. We can represent this trajectory as a 2D `numpy` array. 

In [34]:
def create_position(nframes=1000000):
    """Generate an array holding the  x, y, and z position of a particle as a function of time.
    
    Parameters
    ----------
    nframes: int
        number of frames; more frames increases the time sampling (i.e. the resolution) 
        of the trajectory, but not the amount of time over which it occurs.  Default is 1000000.
        
    Returns
    -------
    time : np.ndarray, shape=(nframes,)
        An array holding the times at which the position was sampled in s
    position : np.ndarray, shape=(nframes, 3)
        An array containing the (x, y, z) position of the particle as a function of time in m.         
    """
    # generate x, y, z positions
    time = np.linspace(0, 4.0*np.pi, nframes) 
    x = np.cos(time)
    y = time/5 + np.sin(time/2.0)
    z = 2*time + 2* np.sin(time)

    # stack them column-wise to create an array with shape (nframes, 3), using numpy's column_stack function
    # This *feels* more natural for a trajectory, since each row is a point in time and each column is a spatial dimension
    position = np.column_stack((x, y, z))

    # Return the time and the position.
    return time, position

Let's generate `numpy` arrays for `time` and `position` to work with:

In [35]:
time, position = create_position()
print('The dimensionality of time is:     ndim=', time.ndim)
print('The shape of time is:              shape=', time.shape)

print('The dimensionality of position is: ndim=', position.ndim)
print('The shape of position is:          shape=', position.shape)

The dimensionality of time is:     ndim= 1
The shape of time is:              shape= (1000000,)
The dimensionality of position is: ndim= 2
The shape of position is:          shape= (1000000, 3)


So time is stored in a 1D array of `shape=(nframes,)`, and the the positions are stored in a two dimensional array, with the first axis, `axis=0`, or the rows, corresponding to the time dimension, and the second axis, `axis=1`, or the columns, corresponding to the spatial dimension. The shape of the position array is `(nframes,3)`, where `nframes` is the number of time snapshots. In other words, the array looks like this:
$$
\begin{pmatrix}
x(t_0) & y(t_0) & z(t_0)\\
x(t_1) & y(t_1) & z(t_1)\\
\vdots & \vdots & \vdots\\
x(t_{\rm nframes-1}) & y(t_{\rm nframes-1}) & z(t_{\rm nframes-1})
\end{pmatrix}
$$

Now say we wanted to examine the position of the particle at the very first time snapshot at $t=0$. Then we would write:

In [36]:
position[0]

array([1., 0., 0.])

to extract it. Notice that indexing starts at 0, as is the convention in Python. What about the third time snapshot?

In [37]:
print('time =', time[2], 's')
position[2]

time = 2.5132766361484705e-05 s


array([1.00000000e+00, 1.75929365e-05, 1.00531065e-04])

In zero-based terms, we would call the "second time snapshot" the zeroth snapshot, and so on. To avoid confusion we'll adopt this convention from now on.

What if we wanted a bunch of frames, but only the 5th through the 72nd? It should have 68 rows:

In [38]:
position[5:73].ndim

2

In [39]:
position[5:73].shape

(68, 3)

Notice the **slicing** notation. Remember, this should be read as

> "Get each row in the array starting from the row at index 5 up to and not including the row at index 73."

We could even sparsely sample the trajectory by slicing out every fifth row in the time dimension giving: 

In [40]:
position[5:73:5].shape

(14, 3)

Now what if we wanted a specific *element* of the array? Indexing works for this too:

In [41]:
position[42, 1]

np.float64(0.00036945166245089196)

This is the y-position of the 42nd snapshot. 

### Example: Numpy slicing

Obtain an array giving the average value of the x, y, z positions (separately) over the time period spanning from the snapshot at index 10 up to and including the snapshot at index 42 as a 1-D array, i.e. 
$$
\langle \mathbf{r}\rangle \equiv \begin{pmatrix}
               \langle x\rangle\\
                \langle y\rangle\\
                \langle z\rangle
                \end{pmatrix}
$$
where e.g. 
$$
\langle x\rangle = \frac{1}{N}\sum_{i=10}^{42} x_i
$$
where $N$ is the number of snapshots in the range $\{10,42\}$.

We can do this by slicing the zeroth axis (rows), then using the `mean` method of the resulting array. To only take a mean across the rows or the time dimension (i.e. a value of the mean for each component, x,y, z, of the position), we must specify the `axis=0` keyword to the `mean` method:

In [ ]:
r_test = position[10:43]
r_test.shape
#r_test.mean()

(33, 3)

In [45]:
r_bar=position[10:43].mean(axis=0)
print(r_bar.shape)
r_bar

(3,)


array([9.99999939e-01, 2.28708173e-04, 1.30690383e-03])

Notice that we collapsed out the time dimension when we performed the ```mean(axis=0)``` operation, and the resulting array has `shape=(3,)`, i.e. it is a 1D array with 3 elements.

What if we wanted the smaller of the two average positions, $\langle y\rangle$ and $\langle z\rangle$,  only?

In [ ]:
r_bar_min = position[10:43, 1:].mean(axis=0).min()
print(r_bar_min)

Docstring:
min(iterable, *[, default=obj, key=func]) -> value
min(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its smallest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the smallest argument.
Type:      builtin_function_or_method

Since slicing and array method operations on arrays often yield arrays, you can chain together operations in this way. This is what qualifies as a *pythonic* way to work with these objects.

### Fancy and boolean indexing

It's also possible to index arrays with lists of indices to select out; these can be repeated and in any order.

In [50]:
A1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

Fancy indexing with a *list of indices*:

In [51]:
A1D[[2, -1, 2, 3]]

array([ 2, 23,  2,  3])

In [56]:
A1D[100*[2]]


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

For our particle, trajectory, we can select arbitrary time steps:

In [57]:
indices = [2, 4, 7, -1, 2]
print(time[indices])
position[indices]

[2.51327664e-05 5.02655327e-05 8.79646823e-05 1.25663706e+01
 2.51327664e-05]


array([[1.00000000e+00, 1.75929365e-05, 1.00531065e-04],
       [9.99999999e-01, 3.51858729e-05, 2.01062131e-04],
       [9.99999996e-01, 6.15752776e-05, 3.51858729e-04],
       [1.00000000e+00, 2.51327412e+00, 2.51327412e+01],
       [1.00000000e+00, 1.75929365e-05, 1.00531065e-04]])

###  Fancy indexing with *booleans*:

In [ ]:
big_values = A1D > 10
#big_values.shape
#A1D.shape
#big_values.dtype
print(A1D)
big_values

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [64]:
#A1D[big_values]
A1D[A1D > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [69]:
# Select out only the even elements of A1D
even_values= A1D % 2 == 0
big_and_even_vals = big_values & even_values
print(A1D[big_and_even_vals])
print(big_and_even_vals)


[12 14 16 18 20 22]
[False False False False False False False False False False False False
  True False  True False  True False  True False  True False  True False]


**Boolean indexing is a convenient way to select parts of an array.** 

## Array arithmetic 

In [70]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 8, 7, -3])

**Array math operations are performed element-wise**:

In [71]:
a + b

array([ 0, 10, 10,  1])

In [72]:
a - b

array([ 2, -6, -4,  7])

In [73]:
a * b

array([ -1,  16,  21, -12])

In [74]:
a / b

array([-1.        ,  0.25      ,  0.42857143, -1.33333333])

Note that integer division returns an array that has data type float, i.e. 

In [ ]:
(a/b).dtype

Trying to raise an integer array to a negative integer power will result in an error:       

In [ ]:
a**b

So we need to cast one of the arrays to a float64 data type first:  

In [ ]:
print(a.astype(np.float64) ** b)
# But I would recommend using np.power for this
print(np.power(np.asarray(a, dtype=np.float64), b))

For multidimensional arrays the same applies:

In [75]:
U = np.array([[1, 2], [3, 4]])
V = np.array([[10, 20], [30, 40]])

In [76]:
U + V

array([[11, 22],
       [33, 44]])

In [77]:
U - V

array([[ -9, -18],
       [-27, -36]])

In [78]:
U * V

array([[ 10,  40],
       [ 90, 160]])

Note that the multiplication here is element-wise, i.e. the product of two arrays is an array where the elements are the products of the corresponding elements of the two arrays. This is in contrast to matrix multiplication, which we will come to in a moment. 

In [ ]:
U / V

### Trajectory example continued: Distance calculation 

Calculate the distance as a function of time from a reference value, e.g., the end point of the trajectory:

In [ ]:
time, position = create_position()
ref = position[-1]
ref

We can write the distance between the particle and the reference position as a function of time as
$$
d(t_i) = |\mathbf{r}(t_i) - \mathbf{r}_\text{ref}| = \sqrt{[x(t_i) - x_\text{ref}]^2 + [y(t_i) - y_\text{ref}]^2 + [z(t_i) - z_\text{ref}]^2} = \sqrt{\sum_{k=0}^2 (r_{i,k} - r_{\text{ref},k})^2}
$$

Let's rewrite this in terms of the difference vector
$$
\Delta\mathbf{r}(t_i) = \mathbf{r}(t_i) - \mathbf{r}_\text{ref}
$$
as
$$
d_i = \sqrt{\Delta\mathbf{r}(t_i) \cdot \Delta\mathbf{r}(t_i)} = \sqrt{\sum_{k=0}^2 \Delta r_{i,k}^2}, 
$$
which will provide intuition about how to write it in numpy. 

First compute _all_ the difference vectors at each time step

In [ ]:
Delta_r = position - ref

In [ ]:
Delta_r.shape

For example at a the time steps $t_0$, $t_1$ and $t_{\rm nframes-1}$:

In [ ]:
Delta_r[[0, 1, -1]]

Square each element:

In [ ]:
Delta_r ** 2

Sum *along the second axis*, i.e. the xyz components:

In [ ]:
distance_squared = (Delta_r ** 2).sum(axis=1)

Notice how I used the parantheses aoove to chain the operations together, i.e. the `sum` method is called on the result of the element-wise squaring of the array. I could have also written this as 
``` python
distance_squared = np.sum(Delta_r**2, axis=1)
```

In [ ]:
distance_squared.shape

Take the square root of each individual $\Delta\mathbf{r}(t_i) \cdot \Delta\mathbf{r}(t_i)$:

In [ ]:
np.sqrt(distance_squared)

The entire computation altogether in one line of code:

In [ ]:
distance =np.sqrt(((position - ref)**2).sum(axis=1))
print(distance.shape)
distance

Which in code looks very similar to

$$
d_i = \sqrt{\sum_{k=0}^2 (r_{i,k} - r_{\text{ref},k})^2}
$$


#### Note on matrices 

Note that multiplication between two arrays is **not** the same as matrix multiplcation. **Arithmetic operations on numpy arrays are performed element-wise.**

In [ ]:
v = np.array([0, -1, 10])
w = np.array([3, 5, -1])
v * w

In [ ]:
A = np.array([[1, 1, 0], [0, 1, 0], [0, 0, 2]])
B = np.array([[2, 0, 0], [-1, 1, 0], [0, 0, 0.5]])
print(A)
print(B)
print(A.shape)
print(B.shape)

The multiplication is _element-wise_ :

In [ ]:
A * B

But there is a method for performing matrix multiplication and dot products (inner products), i.e. 
$$
\mathbf{v}\cdot\mathbf{w} = \sum_{i=0}^2 v_i w_i, \quad {\rm dot~product}\\
\mathbf{A}\mathbf{v} = \sum_{j=0}^2 A_{ij} v_j, \quad {\rm matrix~vector~product}\\
[\mathsf{A}\mathsf{B}]_{ik} = \sum_{j=0}^2 A_{ij} B_{jk} \quad {\rm matrix~multiplication}
$$

In [ ]:
np.dot(v, w)

or with `@` (matrix multiplication operator)

In [ ]:
v @ w

Numpy arrays also have the `dot()` method:

In [ ]:
A.dot(v)

In [ ]:
A.dot(B)

Which is equivalent to: 

In [ ]:
A @ B

More linear algebra functions can be found in the [`numpy.linalg`](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html) module:

In [ ]:
dir(np.linalg)

## Creating new arrays

The `numpy` package provides a number of functions for creating new arrays. For example, we can create an array full of zeros with the `np.zeros` function:

In [ ]:
print(np.zeros((2,3)).shape)
np.zeros((2,3))

where the tuple argument indicates the shape. Similarly an array of ones can be created with the `np.ones` function:

In [ ]:
np.ones((2,3))

A 2D array of boolean data type filled with `True` values can be created with:

In [ ]:
np.ones((2,3), dtype=bool)

The `np.arange` function creates an array of evenly spaced values within a given interval which is equivalent to the 
native python `range` function that we encountered in Week3s lecture on loops
```python
range(start, stop, step)
```

`np.arange` is the equivalent to `range`:

In [ ]:
np.arange(-6, 6, 2)

Although it is more flexible, since it can use float steps:

In [ ]:
np.arange(10, step=0.5)

Although more useful is `np.linspace(start, stop, num)` to make exactly `num` equally distant numbers between `start` and `stop` _inclusive_:

In [ ]:
np.linspace(-6, 6, 13)

## Thinking in arrays 

Say we wanted to displace our particle a full 5 units in each of the $x, y$, and $z$ directions. If you have experience with a language like C, you might be used to writing nested loops like this one to achieve this:

In [ ]:
time, position = create_position()

(We use the `%%time` magic to get the time for a whole code block.)

In [ ]:
%%time
for i in range(position.shape[0]):
    for j in range(position.shape[1]):
        position[i, j] += 5

In [ ]:
position

But one of the main points of `numpy` is performance, so we'd do better to spend as little time as possible doing calculations line by line in the Python interpreter, which is the case in the above loop. Instead we can do:

In [ ]:
time, position = create_position()

In [ ]:
%%time
position += 5

Speed-up for using array operations instead of `for` loops:

In [ ]:
471e-3/601e-6

On my laptop the difference in speed is a factor of $\approx 800$ (you might see speed-ups on the order of 100 to 1000). The larger the array the more pronounced the difference in speed will be, too. The general rule when using `numpy` is to try and put what you're trying to do in terms of operations on whole arrays (or slices of them). For manipulating numerical data in arrays, **always try to avoid Python loops unless absolutely necessary.**

For functions like $\sin$, $\cos$, $\exp$, etc. you can use the functions from the  `numpy` module to operate on arrays element-wise. This is much faster than looping over the array and applying the function to each element individually. This is referred to as a **vectorized** operation. 


As an example of how you can code without loops, consider the function we wrote before in Week3s lecture on basic control flow, which computes the gravitational potential energy of a test mass $m$ at a distance $r$ from the center of a uniform density sphere of total mass $M$ and radius $R$ is given by
$$
U_{\rm grav}(r)=\begin{cases}
-\frac{GMm(3R^2-r^2)}{2R^3} & r\le R\\
-\frac{GMm}{r} & r\gt R
\end{cases}
$$

There we computed the potential energy as a function of distance from the center of the Earth using the following code:

In [ ]:
def U_grav(r,M,R,m): 
    """ Gravitational potential energy of a mass m at a distance r from a uniform density sphere of total mass M and radius R. 
    
    Parameters
    ----------
    r : float 
        Distance from center of the sphere (m).  
    M : float 
        Total mass of the sphere (kg).
    R : float 
        Radius of the sphere (m)
    m : float 
        Mass of test mass (kg).
    
    Returns
    -------
    U : float 
        Gravitational potential energy (J). 
    """
    G=6.67408e-11 # Newton's gravitational constant in units of m^3/(kg s^2)
    if r <= R:
        return -G*M*m*(3*R**2-r**2)/2/R**3
    else:
        return -G*M*m/r

Now with our new knowledge of numpy arrays, we can **vectorize** this code, i.e. write it without loops, as follows:

In [ ]:
def U_grav_vector(r,M,R,m): 
    """ Gravitational potential energy of a mass m at a distance r from a uniform density sphere of total mass M and radius R. 
    
    Parameters
    ----------
    r : float 
        Distance from center of the sphere (m).  
    M : float 
        Total mass of the sphere (kg).
    R : float 
        Radius of the sphere (m)
    m : float 
        Mass of test mass (kg).
    
    Returns
    -------
    U : float 
        Gravitational potential energy (J). 
    """
    G=6.67408e-11 # Newton's gravitational constant in units of m^3/(kg s^2)
    U = np.zeros_like(r)
    ind_le_R = r <= R
    ind_gt_R = np.logical_not(ind_le_R)
    U[ind_le_R] = -G*M*m*(3*R**2-np.square(r[ind_le_R]))/2/R**3
    U[ind_gt_R] = -G*M*m/r[ind_gt_R]
    return U

As before we will evaluate for the Earth on a linearly spaced grid of distances from the center of the Earth to $3\times 10^7~{\rm m}$, and compare the performance of the two implementations:

In [ ]:
R = 6.371e6 # Radius of the Earth in m
M = 5.972e24 # Mass of the Earth in kg 
m = 1.0 # Mass of the test mass in kg
# Create an arry of 10^4 evenly spaced values of r from 0 to 3e7
nr=10000
r = np.linspace(0.0,3.0e7,nr)

In [ ]:
%%timeit
# Version using a loop
# Initialize an array of zeros for U which we will fill up
U = np.zeros_like(r) 
# Populate U
for i in range(nr):
    U[i] = U_grav(r[i],M,R,m)

In [ ]:
%%timeit
# Vectorized version with no loops
U = U_grav_vector(r,M,R,m)

So the speed gain is a factor of $\approx 80$.